version: '3.8'
services:
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8443:443'
    environment:
      DOKUWIKI_USERNAME: admin
      DOKUWIKI_PASSWORD: admin
    volumes:
      - $PWD/dokuwiki_data:/bitnami/dokuwiki
volumes:
  dokuwiki_data:
    driver: local
