version: '3.8'
services:
  dokuwiki:
    image: 'xtremxpert/rpi-dokuwiki'
    container_name: dokuwiki
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8443:443'
    environment:
      DOKUWIKI_USERNAME: admin
      DOKUWIKI_PASSWORD: admin
    volumes:
      - dokuwiki_data:/dokuwiki
volumes:
  dokuwiki_data:
    driver: local
